services:
  # Backend API Service
  - type: web
    name: Pentagon-gymnastics
    runtime: node
    rootDir: ./backend
    buildCommand: npm install && npm run production:setup && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: Pentagon-gymnastics-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

  # Frontend Static Site
  - type: web
    name: Pentagon-gymnastics-frontend
    runtime: static
    rootDir: ./frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://Pentagon-gymnastics.onrender.com/api

databases:
  - name: Pentagon-gymnastics-db
    databaseName: Pentagon_gymnastics
    user: postgres
